---
title: "data_wrangling"
output: github_document
date: "2022-11-21"
---

```{r, include = FALSE}
library(survivoR)
library(tidyverse)
library(stringr)
library(dplyr)
```

```{r, echo = FALSE}
## cleaning Castaway Details dataset: filtering-out non-US seasons, creating personality type variable
castaway_details_US = castaway_details %>% 
  filter(str_detect(castaway_id, '^US')) %>%
  mutate(
    personality_type_binary = ifelse(
      str_detect(personality_type, '^E'), "Extrovert", "Introvert")) %>%
  select(-c(castaway_id, castaway, personality_type))

## Castaways dataset: filtering-out non-US seasons, renaming variables
castaways_US = castaways %>% filter(version == "US") %>%
  select(-c(version, season_name, season, castaway_id, castaway, jury_status, original_tribe)) %>%
  rename(age_during_show = age, days_survived = day)

## joining datasets
survivor_data_final = full_join(castaway_details_US, castaways_US, by = "full_name")

## summarizing the number of contestants per season & adding to joined dataset
contestant_count_df = survivor_data_final %>% group_by(version_season) %>% summarize(contestant_count = n())
survivor_data_final = full_join(survivor_data_final, contestant_count_df, by = "version_season")

## reordering variables, create new variable ethnicity, fix personality type variable
survivor_data_final = survivor_data_final %>%
  select(c("version_season", "full_name", "age_during_show", "race", "poc", "date_of_birth", "date_of_death", "occupation", "gender", "ethnicity", "personality_type_binary", "episode", "days_survived", "order", "contestant_count", "result", "city", "state")) %>% 
    mutate(ethnicity = ifelse(
      str_detect(poc, 'White'), survivor_data_final$poc, survivor_data_final$race)) %>% 
  arrange(version_season) %>%
  mutate(personality_type_binary = as.factor(personality_type_binary))

survivor_data_final_including_2_41_42_43 = survivor_data_final

write.csv(survivor_data_final_including_2_41_42_43, file = "./data/survivor_data_final_including_2_41_42_43.csv")

# preparing data for survival analysis

## season 41 and 42, the longest survival time is 26 days, exclude these seasons
## season 2, the longest survival time is 42 days, exclude this season
## season 43 is incomplete, exclude this season
survivor_data_final <- survivor_data_final %>% 
  filter(version_season != "US02") %>%
  filter(version_season != "US41") %>%
  filter(version_season != "US42") %>%
  filter(version_season != "US43")

## calculating percent NAs for all variables
survivor_data_final %>% summarise_all(list(name = ~sum(is.na(.))/length(.)))

## Saving final dataset as csv file
write.csv(survivor_data_final, file = "./data/survivor_data_final.csv")
```





