---
title: "Final Project Proposal"
author: "Emily Potts (enp2116), Yi Huang (yh3554), Shodai Inose (si2426), Farizah Rob (fir2103)"
date: "2022-11-12"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The tentative project title:

The motivation for this project: We are curious about the implications of self-identified race and personality type to game show survival, as entertainment culture is deeply intertwined with societal biases.

The intended final products:

Our anticipated data sources are the `castaway_details` and `castaways` datasets from the `survivoR` package, which has data from all seasons of the U.S. T.V. show Survivor.

The planned analyses / visualizations / coding challenges: In order to gather sufficient data, we plan to combine several data sets (including `castaway_details` and `castaways`) and tidy them if necessary. Some of our variables of interest have many categories, which could lead to loss of generality. To combat this, we may categorize our variables of interest differently, such as extracting whether a person is an introvert or extrovert from their personality type, or using a POC indicator variable instead of individual races. We plan to perform EDA that visualize the distributions of our variables of interest, including POC, race, ethnicity, gender, personality type, and age. As our main analysis, we plan on doing survival analysis, using the number of days the contestants stay on the show.

The planned timeline: 
- Week of November 13: Merge datasets, clean and tidy the data, create any new variables that might be needed for analysis. Start EDA - create visualizations for the distributions and frequencies of variables of interest. 
- Week of November 21: Continue working on EDA, improve visualizations, create interactive plots and possibly a flex dashboard. Start working on survival analysis code. 
- Week of November 28: Start drafting tables and graphs for the report - work on writing up the report together. 
- Week of December 4: Finalize the report, conduct any additional analyses as needed.

